spring.application.name=fruitapp

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_spr
spring.datasource.username=postgres
spring.datasource.password=sa

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration